/**
 * Pure helpers for decoding and *curating* Claude Code's on-disk session
 * format into a clean, CLI-like transcript.
 *
 * Sessions are JSONL under ~/.claude/projects/<encoded-cwd>/<session-id>.jsonl,
 * one transcript entry per line. The raw stream contains a lot of plumbing the
 * CLI hides — tool results fed back to the model, background-task
 * notifications, slash-command echoes, local-command output, caveats. The
 * curation here mirrors that: it keeps human/assistant text and represents
 * tool calls as compact chips, and drops the noise.
 *
 * The format is not a stable public contract, so everything is defensive:
 * unknown shapes degrade gracefully rather than throwing.
 */

import type { MessagePart, MessageRole, SessionSummary, TranscriptMessage } from '../../shared/types.js'

/**
 * Decode an encoded project directory name back into a best-effort absolute
 * path. Claude Code replaces both '/' and '.' with '-', which is lossy, so the
 * original cannot be perfectly recovered — prefer a `cwd` read from inside a
 * transcript when available.
 */
export function decodeProjectDir(dirName: string): string {
  if (!dirName) return ''
  const withRoot = dirName.startsWith('-') ? dirName.slice(1) : dirName
  return '/' + withRoot.replace(/-/g, '/')
}

/** Parse a timestamp that may be an ISO string or epoch ms into epoch ms. */
export function parseTimestamp(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value
  if (typeof value === 'string') {
    const ms = Date.parse(value)
    return Number.isNaN(ms) ? null : ms
  }
  return null
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/* ----------------------------------------------------------------------------
 * Noise detection — text the CLI never shows as conversation.
 * ------------------------------------------------------------------------- */

/** Wrapper tags injected by the client/runtime, not real conversation. */
const NOISE_TAGS = new Set([
  'task-notification',
  'local-command-caveat',
  'local-command-stdout',
  'command-name',
  'command-message',
  'command-args',
  'command-stdout',
  'command-contents',
  'system-reminder',
  'bash-input',
  'bash-stdout',
  'bash-stderr'
])

/** Phrases that mark a system-injected pseudo-message. */
const NOISE_PREFIXES = [
  'Command running in background with ID:',
  'Caveat: The messages below were generated by the user'
]

/** True when a chunk of text is runtime plumbing rather than conversation. */
export function isNoiseText(text: string): boolean {
  const trimmed = text.trim()
  if (!trimmed) return true
  if (NOISE_PREFIXES.some((prefix) => trimmed.startsWith(prefix))) return true
  const tag = trimmed.match(/^<\/?([a-z0-9-]+)\s*>/i)
  if (tag && NOISE_TAGS.has(tag[1].toLowerCase())) return true
  return false
}

/* ----------------------------------------------------------------------------
 * Tool rendering.
 * ------------------------------------------------------------------------- */

/** Build a short, human-friendly detail line for a tool call. */
export function toolDetail(input: unknown): string {
  if (!isRecord(input)) return ''
  const candidates = ['command', 'file_path', 'path', 'pattern', 'url', 'description', 'prompt', 'query']
  for (const key of candidates) {
    const value = input[key]
    if (typeof value === 'string' && value.trim()) return truncate(value.trim(), 120)
  }
  return ''
}

/* ----------------------------------------------------------------------------
 * Content -> parts.
 * ------------------------------------------------------------------------- */

/**
 * Convert a message `content` (string or block array) into renderable parts,
 * dropping noise. Tool results are intentionally omitted — they are plumbing
 * fed back to the model, not conversation.
 */
export function contentToParts(content: unknown): MessagePart[] {
  if (typeof content === 'string') {
    return isNoiseText(content) ? [] : [{ kind: 'text', text: content.trim() }]
  }
  if (!Array.isArray(content)) return []

  const parts: MessagePart[] = []
  for (const block of content) {
    if (typeof block === 'string') {
      if (!isNoiseText(block)) parts.push({ kind: 'text', text: block.trim() })
      continue
    }
    if (!isRecord(block)) continue

    switch (block.type) {
      case 'text': {
        const text = typeof block.text === 'string' ? block.text : ''
        if (text.trim() && !isNoiseText(text)) parts.push({ kind: 'text', text: text.trim() })
        break
      }
      case 'thinking': {
        const text = typeof block.thinking === 'string' ? block.thinking : ''
        if (text.trim()) parts.push({ kind: 'thinking', text: text.trim() })
        break
      }
      case 'tool_use': {
        const name = typeof block.name === 'string' ? block.name : 'tool'
        parts.push({ kind: 'tool', name, detail: toolDetail(block.input) })
        break
      }
      // tool_result and any unknown block types are dropped.
      default:
        break
    }
  }
  return parts
}

/** Map a raw entry to one of our display roles. */
function classifyRole(entry: Record<string, unknown>): MessageRole {
  const type = typeof entry.type === 'string' ? entry.type : ''
  if (type === 'user') return 'user'
  if (type === 'assistant') return 'assistant'
  if (type === 'system' || type === 'summary') return 'system'
  const message = isRecord(entry.message) ? entry.message : undefined
  const role = message && typeof message.role === 'string' ? message.role : ''
  if (role === 'assistant') return 'assistant'
  return 'user'
}

/** Pull the content out of an entry, whether nested under `message` or inline. */
function entryContent(entry: Record<string, unknown>): unknown {
  if (isRecord(entry.message) && 'content' in entry.message) return entry.message.content
  if ('content' in entry) return entry.content
  return ''
}

/**
 * Convert one parsed JSONL entry into a curated TranscriptMessage, or null when
 * it carries nothing worth showing (pure tool plumbing, noise, meta).
 */
export function entryToMessage(entry: unknown, index: number): TranscriptMessage | null {
  if (!isRecord(entry)) return null

  // Hide standalone meta entries (auto summaries, system bookkeeping).
  const type = typeof entry.type === 'string' ? entry.type : ''
  if (type === 'summary' || type === 'system') return null

  const role = classifyRole(entry)
  const parts = contentToParts(entryContent(entry))
  if (parts.length === 0) return null

  const id =
    (typeof entry.uuid === 'string' && entry.uuid) ||
    (typeof entry.id === 'string' && entry.id) ||
    `entry-${index}`

  return { id, role, parts, timestamp: parseTimestamp(entry.timestamp) }
}

/** Parse the raw text of a .jsonl file into curated transcript messages. */
export function parseTranscript(raw: string): TranscriptMessage[] {
  const messages: TranscriptMessage[] = []
  const lines = raw.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()
    if (!line) continue
    let parsed: unknown
    try {
      parsed = JSON.parse(line)
    } catch {
      continue // tolerate truncated / partially written lines
    }
    const message = entryToMessage(parsed, i)
    if (message) messages.push(message)
  }
  return messages
}

/** The earliest `cwd` recorded anywhere in a session's raw entries, if any. */
export function extractCwd(raw: string): string | null {
  for (const line of raw.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed) continue
    try {
      const parsed = JSON.parse(trimmed)
      if (isRecord(parsed) && typeof parsed.cwd === 'string' && parsed.cwd) return parsed.cwd
    } catch {
      continue
    }
  }
  return null
}

/** First displayable text from a message's parts, for use as a title. */
function firstText(message: TranscriptMessage | undefined): string {
  if (!message) return ''
  const part = message.parts.find((p) => p.kind === 'text')
  return part && part.kind === 'text' ? part.text : ''
}

/**
 * Build a SessionSummary from a session's raw transcript text. `fallbackCwd` is
 * used when no `cwd` is embedded. `title` overrides the derived title (e.g. a
 * custom /rename title supplied by the SDK).
 */
export function summarizeSession(args: {
  sessionId: string
  projectDir: string
  raw: string
  fallbackCwd: string
  title?: string
  gitBranch?: string
}): SessionSummary {
  const { sessionId, projectDir, raw, fallbackCwd, title, gitBranch } = args
  const messages = parseTranscript(raw)
  const firstUser = messages.find((m) => m.role === 'user')
  const timestamps = messages
    .map((m) => m.timestamp)
    .filter((t): t is number => t !== null)
  return {
    sessionId,
    projectDir,
    cwd: extractCwd(raw) ?? fallbackCwd,
    title: truncateTitle(title || firstText(firstUser) || '(no prompt)'),
    gitBranch,
    createdAt: timestamps.length ? Math.min(...timestamps) : null,
    lastActivity: timestamps.length ? Math.max(...timestamps) : null,
    messageCount: messages.length
  }
}

/** Collapse whitespace and clip a prompt to a one-line title. */
export function truncateTitle(text: string, max = 80): string {
  return truncate(text.replace(/\s+/g, ' ').trim() || '(no prompt)', max)
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text
  return text.slice(0, max - 1).trimEnd() + '…'
}
