import { describe, expect, it } from 'vitest'
import {
  contentToParts,
  decodeProjectDir,
  entryToMessage,
  extractCwd,
  isNoiseText,
  parseTimestamp,
  parseTranscript,
  summarizeSession,
  toolDetail,
  truncateTitle
} from './transcript.js'

describe('decodeProjectDir', () => {
  it('reconstructs an absolute path from an encoded dir', () => {
    expect(decodeProjectDir('-home-user-Proj')).toBe('/home/user/Proj')
  })
  it('handles an empty string', () => {
    expect(decodeProjectDir('')).toBe('')
  })
})

describe('parseTimestamp', () => {
  it('parses ISO strings and epoch numbers', () => {
    expect(parseTimestamp('2026-01-01T00:00:00.000Z')).toBe(Date.parse('2026-01-01T00:00:00.000Z'))
    expect(parseTimestamp(1700000000000)).toBe(1700000000000)
  })
  it('returns null for junk', () => {
    expect(parseTimestamp('nope')).toBeNull()
    expect(parseTimestamp(undefined)).toBeNull()
  })
})

describe('isNoiseText', () => {
  it('flags wrapper tags', () => {
    expect(isNoiseText('<task-notification>\n<task-id>x</task-id>')).toBe(true)
    expect(isNoiseText('<local-command-stdout>Set effort</local-command-stdout>')).toBe(true)
    expect(isNoiseText('<command-name>/effort</command-name>')).toBe(true)
  })
  it('flags background-task and caveat phrases', () => {
    expect(isNoiseText('Command running in background with ID: abc123')).toBe(true)
    expect(isNoiseText('Caveat: The messages below were generated by the user')).toBe(true)
  })
  it('treats real prose as conversation', () => {
    expect(isNoiseText('Please refactor the auth module')).toBe(false)
  })
  it('treats empty/whitespace as noise', () => {
    expect(isNoiseText('   ')).toBe(true)
  })
})

describe('toolDetail', () => {
  it('prefers command, then file path', () => {
    expect(toolDetail({ command: 'npm test' })).toBe('npm test')
    expect(toolDetail({ file_path: '/a/b.ts' })).toBe('/a/b.ts')
  })
  it('returns empty for unknown shapes', () => {
    expect(toolDetail(null)).toBe('')
    expect(toolDetail({ foo: 1 })).toBe('')
  })
})

describe('contentToParts', () => {
  it('keeps text, renders tool_use as a chip, drops tool_result', () => {
    const content = [
      { type: 'text', text: 'On it.' },
      { type: 'tool_use', name: 'Bash', input: { command: 'npm test' } },
      { type: 'tool_result', content: [{ type: 'text', text: 'passed' }] }
    ]
    expect(contentToParts(content)).toEqual([
      { kind: 'text', text: 'On it.' },
      { kind: 'tool', name: 'Bash', detail: 'npm test' }
    ])
  })
  it('drops noise text blocks', () => {
    const content = [{ type: 'text', text: '<command-name>/effort</command-name>' }]
    expect(contentToParts(content)).toEqual([])
  })
  it('handles a bare string', () => {
    expect(contentToParts('hello')).toEqual([{ kind: 'text', text: 'hello' }])
  })
  it('captures thinking blocks', () => {
    expect(contentToParts([{ type: 'thinking', thinking: 'hmm' }])).toEqual([
      { kind: 'thinking', text: 'hmm' }
    ])
  })
})

describe('entryToMessage', () => {
  it('maps an assistant entry into parts', () => {
    const entry = {
      type: 'assistant',
      uuid: 'a1',
      timestamp: '2026-01-01T00:00:00.000Z',
      message: { role: 'assistant', content: [{ type: 'text', text: 'hi' }] }
    }
    expect(entryToMessage(entry, 0)).toEqual({
      id: 'a1',
      role: 'assistant',
      parts: [{ kind: 'text', text: 'hi' }],
      timestamp: Date.parse('2026-01-01T00:00:00.000Z')
    })
  })
  it('hides system and summary meta entries', () => {
    expect(entryToMessage({ type: 'summary', summary: 'x' }, 0)).toBeNull()
    expect(entryToMessage({ type: 'system', content: 'boot' }, 0)).toBeNull()
  })
  it('hides messages that are pure noise or tool results', () => {
    const taskNotif = {
      type: 'user',
      message: { role: 'user', content: '<task-notification>done</task-notification>' }
    }
    const toolResult = {
      type: 'user',
      message: { role: 'user', content: [{ type: 'tool_result', content: 'ok' }] }
    }
    expect(entryToMessage(taskNotif, 0)).toBeNull()
    expect(entryToMessage(toolResult, 1)).toBeNull()
  })
  it('synthesizes an id when none is present', () => {
    const entry = { type: 'user', message: { role: 'user', content: 'x' } }
    expect(entryToMessage(entry, 7)?.id).toBe('entry-7')
  })
})

describe('parseTranscript', () => {
  const raw = [
    JSON.stringify({
      type: 'user',
      uuid: 'u1',
      timestamp: '2026-01-01T00:00:00.000Z',
      cwd: '/work/proj',
      message: { role: 'user', content: 'Do the thing' }
    }),
    '',
    'not json',
    JSON.stringify({
      type: 'user',
      message: { role: 'user', content: '<command-name>/effort</command-name>' }
    }),
    JSON.stringify({
      type: 'assistant',
      uuid: 'a1',
      timestamp: '2026-01-01T00:01:00.000Z',
      message: { role: 'assistant', content: [{ type: 'text', text: 'Done' }] }
    })
  ].join('\n')

  it('keeps real messages and drops noise/invalid lines', () => {
    const messages = parseTranscript(raw)
    expect(messages).toHaveLength(2)
    expect(messages[0].parts).toEqual([{ kind: 'text', text: 'Do the thing' }])
    expect(messages[1].role).toBe('assistant')
  })

  it('extracts the embedded cwd', () => {
    expect(extractCwd(raw)).toBe('/work/proj')
  })

  it('summarizes a session, preferring an explicit title', () => {
    const summary = summarizeSession({
      sessionId: 's1',
      projectDir: '-work-proj',
      raw,
      fallbackCwd: '/fallback',
      title: 'Renamed Session',
      gitBranch: 'main'
    })
    expect(summary).toMatchObject({
      sessionId: 's1',
      cwd: '/work/proj',
      title: 'Renamed Session',
      gitBranch: 'main',
      messageCount: 2
    })
  })

  it('falls back to the first prompt when no title is given', () => {
    const summary = summarizeSession({
      sessionId: 's2',
      projectDir: 'd',
      raw,
      fallbackCwd: '/fallback'
    })
    expect(summary.title).toBe('Do the thing')
    expect(summary.cwd).toBe('/work/proj')
  })
})

describe('truncateTitle', () => {
  it('collapses whitespace and clips long titles', () => {
    expect(truncateTitle('a\n  b   c')).toBe('a b c')
    const long = truncateTitle('x'.repeat(200), 10)
    expect(long).toHaveLength(10)
    expect(long.endsWith('…')).toBe(true)
  })
  it('falls back for empty input', () => {
    expect(truncateTitle('   ')).toBe('(no prompt)')
  })
})
